apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: nginx-blue-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-blue
  type: ClusterIP
