apiVersion: v1
kind: Service
metadata:
  labels:
    app: portal-client-deploy
  name: portal-client-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 4200
  - name: https
    port: 443
    protocol: TCP
    targetPort: 4200
  selector:
    tier: frontend
  type: ClusterIP
