apiVersion: v1
kind: Service
metadata:
  labels:
    app: portal-api-deploy
  name: portal-api-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    env: prod
    tier: portal-backend
  type: ClusterIP
